name: testcase
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # UI & Animation Packages
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.3    
  dots_indicator: ^3.0.0
  flutter_rating_bar: ^4.0.1

  # State Management & Utilities  
  equatable: ^2.0.5

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Noto
      fonts:
        - asset: assets/fonts/noto_sans/NotoSansKR-Regular.ttf
